### ISSUE TITLE
Convergence for Bi-Laplace equation

### ISSUE THREAD

**Issue by alecjacobson** [kinnala/sp.fem#20]
I'm having trouble getting my solution for the bi-laplace equation using Morley/Argyris elements to converge. 

As a test case, I'm trying to reproduce the (bi)harmonic function g(x,y) = -x^2+y^2 by solving Lap^2 f(x,y) = 0 subject to f(x,y) = g(x,y), Grad f(x,y) . n(x,y) = Grad g(x,y) . n(x,y) on the boundary. Let's first agree that f = g is the solution to this bi-Laplace PDE. I'm trying to solve this using Morley elements with the following:

``` python
# adapated from http://scicomp.stackexchange.com/a/25308/11527
from spfem.mesh import MeshTri
from spfem.asm import AssemblerGlobal
from spfem.element import ElementGlobalMorley
from spfem.element import ElementGlobalArgyris
from spfem.utils import direct,const_cell
import numpy as np

# define mesh
for r in range(1,6):
   m=MeshTri()
   m.refine(r)

   # define element and assemble the stiffness matrix and load vector
   e1=ElementGlobalMorley()
   #e1=ElementGlobalArgyris()
   a=AssemblerGlobal(m,e1)

   # <Hess u, Hess v>
   def bilinear(ddu,ddv):
      return ddu[0][0]*ddv[0][0]+\
             ddu[0][1]*ddv[0][1]+\
             ddu[1][0]*ddv[1][0]+\
             ddu[1][1]*ddv[1][1]

   # Zero right-hand side
   def F(x):
      return 0

   A=a.iasm(bilinear)
   f=a.iasm(lambda v,x: F(x)*v)

   # find boundary and interior DOFs
   bnd_nodes=m.boundary_nodes()
   bnd_facets=m.boundary_facets()
   bnd_facets_mid=0.5*(m.p[:,m.facets[0,bnd_facets]]+\
                       m.p[:,m.facets[1,bnd_facets]])

   d1=a.dofnum_u.getdofs(N=bnd_nodes)
   d2=a.dofnum_u.getdofs(F=bnd_facets)

   I=np.setdiff1d(np.arange(a.dofnum_u.N),np.union1d(d1,d2))

   # set boundary conditions
   x=np.zeros(A.shape[0])

   # Set boundary values to g(x,y) = -x^2 +y^2
   def G1(x,y):
      return -x*x+y*y

   # Set boundary normal derivatives to Grad g(x,y) . n(x,y)
   def G2(x,y):
      def G2_single(x,y):
         if x == 0:
            return -2*y
         elif x == 1:
            return 2*y
         elif y == 0:
            return 2*x
         elif y == 1:
            return -2*x
         else:
            # this should never happen
            print "error: "+x+","+y
      return map(G2_single,x,y)

   # check orientation of boundary normals from sign of jacobin determinant
   tris=np.ones(m.t.shape[1])
   flip=np.nonzero((a.mapping.detDF(np.array([[0]]))<0).flatten())[0]
   tris[flip]=-1.0
   ori=tris[m.f2t[0,bnd_facets]]

   x[d1]=G1(m.p[0,bnd_nodes],m.p[1,bnd_nodes])
   x[d2]=ori*G2(bnd_facets_mid[0,:],bnd_facets_mid[1,:])

   # solve the system
   x=direct(A,f,I=I,x=x)
   xverts=x[a.dofnum_u.n_dof[0,:]]

   # Linf norm
   print "% 9d %0.4f" % (len(xverts), max(abs((G1(m.p[0],m.p[1])-xverts))))

```

So for _**Morley elements**_, I'm seeing:

```
        9 0.0625
       25 0.0514
       81 0.0567
      289 0.0667
     1089 0.0701
```

For _**Argyris elements**_, (swapping `ElementGlobalMorley` for `ElementGlobalArgyris`) I'm seeing:

```
        9 0.0474
       25 0.1285
       81 0.1158
      289 0.1202
...
```

Is there a problem with how I'm setting up the problem?

**Comment by kinnala** [comment]
My guess is that the problem is related to the fact that Argyris has more degrees of freedom on each node, such as the first and the second derivatives. You must constraint these degrees of freedom as well to get a proper solution.

I will take a closer look on Saturday. I'm currently travelling and cannot access my computer.

**Comment by kinnala** [comment]
It seems that there are two mistakes in the code. One is mine: on the definition of `flip` the inequality should be `>` if you want to define exterior normal gradient. Second mistake is that the normal derivative is computed wrong. Try the following:

`` 54    def G2(x,y):                                                                                                                                                               
 55       def G2_single(x,y):                                                                                                                                                     
 56          if x == 0:                                                                                                                                                           
 57             return 0                                                                                                                                                          
 58          elif x == 1:                                                                                                                                                         
 59             return -2                                                                                                                                                         
 60          elif y == 0:                                                                                                                                                         
 61             return 0                                                                                                                                                          
 62          elif y == 1:                                                                                                                                                         
 63             return 2                                                                                                                                                          
 64          else:                                                                                                                                                                
 65             # this should never happen                                                                                                                                        
 66             print "error: "+x+","+y                                                                                                                                           
 67       return map(G2_single,x,y)

**Comment by kinnala** [comment]
```
from spfem.mesh import MeshTri
from spfem.asm import AssemblerGlobal
from spfem.element import ElementGlobalMorley
from spfem.element import ElementGlobalArgyris
from spfem.utils import direct,const_cell
import numpy as np

# define mesh
for r in range(1,5):
   m=MeshTri()
   m.refine(r)

   # define element and assemble the stiffness matrix and load vector
   e1=ElementGlobalMorley()
   #e1=ElementGlobalArgyris()
   a=AssemblerGlobal(m,e1)

   # <Hess u, Hess v>
   def bilinear(ddu,ddv):
      return ddu[0][0]*ddv[0][0]+\
             ddu[0][1]*ddv[0][1]+\
             ddu[1][0]*ddv[1][0]+\
             ddu[1][1]*ddv[1][1]

   # Zero right-hand side
   def F(x):
      return 0

   A=a.iasm(bilinear)
   f=a.iasm(lambda v,x: F(x)*v)

   # find boundary and interior DOFs
   bnd_nodes=m.boundary_nodes()
   bnd_facets=m.boundary_facets()
   bnd_facets_mid=0.5*(m.p[:,m.facets[0,bnd_facets]]+\
                       m.p[:,m.facets[1,bnd_facets]])

   d1=a.dofnum_u.getdofs(N=bnd_nodes)
   d2=a.dofnum_u.getdofs(F=bnd_facets)

   I=np.setdiff1d(np.arange(a.dofnum_u.N),np.union1d(d1,d2))

   # set boundary conditions
   x=np.zeros(A.shape[0])

   # Set boundary values to g(x,y) = -x^2 +y^2
   def G1(x,y):
      return -x*x+y*y # (-2*x,2*y)

   # Set boundary normal derivatives to Grad g(x,y) . n(x,y)
   def G2(x,y):
      def G2_single(x,y):
         if x == 0:
            return 0
         elif x == 1:
            return -2
         elif y == 0:
            return 0
         elif y == 1:
            return 2
         else:
            # this should never happen
            print "error: "+x+","+y
      return map(G2_single,x,y)

   # check orientation of boundary normals from sign of jacobin determinant
   tris=np.ones(m.t.shape[1])
   flip=np.nonzero((a.mapping.detDF(np.array([[0]]))>0).flatten())[0]
   tris[flip]=-1.0
   ori=tris[m.f2t[0,bnd_facets]]

   x[d1]=G1(m.p[0,bnd_nodes],m.p[1,bnd_nodes])
   x[d2]=ori*G2(bnd_facets_mid[0,:],bnd_facets_mid[1,:])

   # solve the system
   x=direct(A,f,I=I,x=x)
   xverts=x[a.dofnum_u.n_dof[0,:]]

   # Linf norm
   #print "% 9d %0.4f" % (len(xverts), max(abs((G1(m.p[0],m.p[1])-xverts))))
   # Linf norm
   print "% 9d %0.4f" % (len(xverts), np.sum(a.iposteriori(lambda u,x:u-G1(x[0],x[1]),x)))

```

**Comment by alecjacobson** [comment]
Thanks! That was a silly error on my part.

Regarding the Argyris elements, how do I constraint the additional DOFs without affecting the solution? As I understand, once I fix the values on the boundary and the normal derivatives on the boundary, there's only a unique biharmonic solution. So won't fixing other DOFs at the boundary dive ate from the solution (unless I had an oracle that could tell me the solution so that I can sample its boundary conditions perfectly a head of time)?

**Comment by kinnala** [comment]
Let u be the solution. For example, on the bottom boundary of the unit square you know the value of u_xx (two partial derivatives with respect to x) since you know what u restricted to the boundary will be. AFAIK, you should constraint the DOFs accordingly. This can be tedious.

Note that I have not yet solved any biharmonic problems with non-homogeneous boundary conditions myself so this is just my guessing.

**Comment by alecjacobson** [comment]
I see what you mean. So I will need to constrain any "extra" degrees of
freedom that _only_ affect the value along the boundary.
